language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-entity' ]; then cd .. && eval "mv $currentfolder generator-entity" && cd generator-entity; fi

